---

- name: Verify and configure SSH access
  ansible.builtin.import_tasks: ssh.yml

- name: Set up base user and directories
  ansible.builtin.import_tasks: user.yml

- name: Install prerequisites
  ansible.builtin.import_tasks: prereqs.yml

- name: Configure firewall
  ansible.builtin.import_tasks: firewall.yml

- name: Authorize CI/CD deploy key
  ansible.builtin.import_tasks: authorize_ci_key.yml

...
