---

- name: Set up base user and directories
  ansible.builtin.import_tasks: user.yml

- name: Install prerequisites
  ansible.builtin.import_tasks: prereqs.yml

- name: Configure firewall
  ansible.builtin.import_tasks: firewall.yml

...
