"""
app.py

Flask web app for browsing top PvP Pokemon rankings with their ideal IVs.

Routes:
    GET /                -> HTML table (league/category/count selectable via query params)
    GET /api/rankings     -> same data as JSON

Data is read from precomputed/<league>_<category>.json, which is generated by
generate_cache.py on a schedule (systemd timer/cron) -- NOT computed live on
each request. See generate_cache.py for details.

Run:
    python app.py
    then open http://127.0.0.1:5000
"""
import json
import logging
import os
from pathlib import Path

from flask import Flask, jsonify, render_template, request
from dotenv import load_dotenv
load_dotenv() # no-op in production if there's no .env file present
              # Create the .env file locally and add FLASK_DEBUG=true if needed.

from pvpoke_data import LEAGUE_CP_CAPS
from build_pokemon_list import build_list, build_low_atk_list, build_high_atk_list

app = Flask(__name__)
logger = logging.getLogger(__name__)

CATEGORIES = ["overall", "leads", "closers", "attackers", "switches", "chargers"]
PRECOMPUTED_DIR = Path(__file__).parent / "precomputed"


def _parse_query_args():
    league = request.args.get("league", "great")
    category = request.args.get("category", "overall")
    n = request.args.get("n", 100, type=int)

    if league not in LEAGUE_CP_CAPS:
        league = "great"
    if category not in CATEGORIES:
        category = "overall"
    n = max(1, min(n, 500))

    return league, category, n


def get_pokemon(league: str, category: str, n: int) -> list[dict]:
    """
    Read precomputed results for a league/category and slice to the requested
    count. Falls back to a live (slow) build only if the cache file doesn't
    exist yet -- e.g. right after a fresh deploy, before generate_cache.py has
    run for the first time. This keeps the site usable on day one without
    silently serving nothing, while still making the fast path the norm.
    """
    cache_file = PRECOMPUTED_DIR / f"{league}_{category}.json"

    if cache_file.exists():
        with open(cache_file) as f:
            data = json.load(f)
        return data[:n]

    logger.warning(
        "No precomputed cache for %s/%s -- falling back to a live build. "
        "Run generate_cache.py to avoid this on future requests.",
        league, category,
    )
    return build_list(league, category, n)


@app.route("/")
def index():
    league, category, n = _parse_query_args()
    pokemon = get_pokemon(league, category, n)
    low_atk_list = build_low_atk_list(pokemon)
    high_atk_list = build_high_atk_list(pokemon)

    return render_template(
        "index.html",
        pokemon=pokemon,
        low_atk_list=low_atk_list,
        high_atk_list=high_atk_list,
        league=league,
        category=category,
        n=n,
        leagues=LEAGUE_CP_CAPS.keys(),
        categories=CATEGORIES,
    )


@app.route("/api/rankings")
def api_rankings():
    league, category, n = _parse_query_args()
    pokemon = get_pokemon(league, category, n)
    return jsonify(pokemon)


if __name__ == "__main__":
    debug_mode = os.environ.get("FLASK_DEBUG", "false").lower() == "true"
    app.run(debug=debug_mode)
