---

- name: Create SSH Key to Droplet
  digitalocean.cloud.ssh_key:
    state: present
    token: "{{ digitalocean_token }}"
    public_key: "{{ admin_ssh_public_key }}"
    name: "pvpokedeployer-key"
  register: ssh_key

...